# Auto-generated by py2gh from examples/truss2d.ghx (a parametric 2D truss).
#   py2gh --to-python examples/truss2d.ghx -o examples/truss2d.py
#
# Best-effort reconstruction: arithmetic/comparison/boolean/geometry-constructor
# components decompile to real Python; geometry/solid components that have no
# native Python form are emitted as gh("Component Name", ...) placeholders.
# Inputs shown as None are unwired params holding typed-in values in Grasshopper.

t1 = gh("Surface", )  # component has no native Python form
t2 = gh("Curve", )  # component has no native Python form
v1 = 8.0
t3 = gh("Divide Curve", t2, v1, None)  # component has no native Python form
t5 = gh("End Points", t2)  # component has no native Python form
t10 = gh("Deconstruct", t5[0])  # component has no native Python form
t12 = (t10[0], t10[1], None)
t11 = gh("Deconstruct", t5[1])  # component has no native Python form
t13 = (t11[0], t11[1], None)
t4 = gh("Line", t12, t13)  # component has no native Python form
t7 = gh("Unit Z", None)  # component has no native Python form
t6 = gh("Extremes", t2, t7)  # component has no native Python form
t8 = gh("Deconstruct", t6[1])  # component has no native Python form
t9 = (None - None)
v2 = 5.0
t16 = gh("Range", None, v2)  # component has no native Python form
t15 = (t16, t16, None)
t14 = gh("Iso Curve", t1, t15)  # component has no native Python form
t17 = gh("Divide Curve", None, v1, None)  # component has no native Python form
t26 = gh("Deconstruct", t3[0])  # component has no native Python form
t25 = gh("Deconstruct", t17[0])  # component has no native Python form
t27 = (t26[0], t26[1], t25[2])
t18 = gh("Line", t3[0], t27)  # component has no native Python form
t20 = gh("Number", )  # component has no native Python form
t19 = gh("Cull Index", t3[0], t20, None)  # component has no native Python form
t21 = gh("PolyLine", t3[0], None)  # component has no native Python form
v4 = 0.0
t32 = gh("Cull Index", t27, v4, None)  # component has no native Python form
t22 = gh("Line", t19, t32)  # component has no native Python form
t23 = gh("Stream Filter", )  # component has no native Python form
v3 = 0.0
v6 = 0.9
t24 = (-v6)
t28 = gh("Offset Surface", t1, t24, None)  # component has no native Python form
t29 = gh("Iso Curve", t28, t15)  # component has no native Python form
t30 = gh("Curve", )  # component has no native Python form
t31 = gh("PolyLine", t27, None)  # component has no native Python form
t33 = gh("Join Curves", t21, None)  # component has no native Python form
t34 = gh("Join Curves", t31, None)  # component has no native Python form
t35 = gh("Join Curves", t33, None)  # component has no native Python form
t38 = gh("Flatten Tree", t35, None)  # component has no native Python form
v7 = 0.02
v5 = 1.0
t36 = gh("Pipe", t38, v7, v5)  # component has no native Python form
t37 = gh("Solid Union", t36)  # component has no native Python form
