# Auto-generated by py2gh from examples/truss2d.ghx (a parametric 2D truss).
#   py2gh --to-python examples/truss2d.ghx -o examples/truss2d.py
#
# Geometry/utility components now decompile to native calls (line, divide_curve,
# polyline, join_curves, pipe, solid_union, ...); a few unmapped components remain
# as gh("Name", ...). Unwired inputs show their typed-in value; geometry typed
# into an input appears as internal("<gh-type>").

t1 = gh("Surface", )  # component has no native Python form
t2 = gh("Curve", )  # component has no native Python form
v1 = 8.0
t3 = divide_curve(t2, v1, False)
t5 = end_points(t2)
t10 = deconstruct(t5[0])
t12 = (t10[0], t10[1], 0.0)
t11 = deconstruct(t5[1])
t13 = (t11[0], t11[1], 0.0)
t4 = line(t12, t13)
t7 = unit_z(1.0)
t6 = gh("Extremes", t2, t7)  # component has no native Python form
t8 = deconstruct(t6[1])
t9 = (None - None)
v2 = 5.0
t16 = gh("Range", internal("gh_interval1d"), v2)  # component has no native Python form
t15 = (t16, t16, 0.0)
t14 = iso_curve(t1, t15)
t17 = divide_curve(None, v1, False)
t26 = deconstruct(t3[0])
t25 = deconstruct(t17[0])
t27 = (t26[0], t26[1], t25[2])
t18 = line(t3[0], t27)
t20 = gh("Number", )  # component has no native Python form
t19 = cull_index(t3[0], t20, True)
t21 = polyline(t3[0], False)
v4 = 0.0
t32 = cull_index(t27, v4, True)
t22 = line(t19, t32)
t23 = gh("Stream Filter", )  # component has no native Python form
v3 = 0.0
v6 = 0.9
t24 = (-v6)
t28 = offset_surface(t1, t24, True)
t29 = iso_curve(t28, t15)
t30 = gh("Curve", )  # component has no native Python form
t31 = polyline(t27, False)
t33 = join_curves(t21, False)
t34 = join_curves(t31, False)
t35 = join_curves(t33, False)
t38 = gh("Flatten Tree", t35, '{0}')  # component has no native Python form
v7 = 0.02
v5 = 1.0
t36 = pipe(t38, v7, v5)
t37 = solid_union(t36)
